[mgr]
show_hidden = false
scrolloff = 5

[preview]
wrap = "yes"

[[mgr.prepend_keymap]]
on = ["g", "g"]
run = "cd ~/tui/illustrations"
desc = "go to tui illustrations"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "go to downloads"
